### ISSUE TITLE
Missing loop variable causes syntax highlighting parser panic

### ISSUE THREAD

**Issue by sholderbach** [nushell/engine-q#601]
## Found by:

1. Enter `for x in  0..5 {}`
2. Move cursor behind `x` to remove it for replacement
3. hit backspace

## MRE:

1. Type `for in`

## Output

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', crates/nu-parser/src/parser.rs:1913:47


stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::panic_bounds_check
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:76:5
   3: nu_parser::parser::parse_var_with_opt_type
             at ./crates/nu-parser/src/parser.rs:1913:47
   4: nu_parser::parser::parse_multispan_value
             at ./crates/nu-parser/src/parser.rs:401:30
   5: nu_parser::parser::parse_internal_call
             at ./crates/nu-parser/src/parser.rs:581:30
   6: nu_parser::parser::parse_call
             at ./crates/nu-parser/src/parser.rs:729:27
   7: nu_parser::parser::parse_expression
             at ./crates/nu-parser/src/parser.rs:3132:9
   8: nu_parser::parser::parse_statement
             at ./crates/nu-parser/src/parser.rs:3232:31
   9: nu_parser::parser::parse_block::{{closure}}
             at ./crates/nu-parser/src/parser.rs:3365:35
  10: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/adapters/map.rs:84:28
  11: core::iter::traits::iterator::Iterator::fold
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/traits/iterator.rs:2171:21
  12: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/adapters/map.rs:124:9
  13: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/traits/iterator.rs:737:9
  14: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/vec/spec_extend.rs:40:17
  15: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/vec/spec_from_iter_nested.rs:56:9
  16: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/vec/spec_from_iter.rs:33:9
  17: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/vec/mod.rs:2517:9
  18: core::iter::traits::iterator::Iterator::collect
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/traits/iterator.rs:1745:9
  19: <nu_protocol::ast::block::Block as core::convert::From<T>>::from
             at ./crates/nu-protocol/src/ast/block.rs:61:20
  20: <T as core::convert::Into<U>>::into
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/convert/mod.rs:542:9
  21: nu_parser::parser::parse_block
             at ./crates/nu-parser/src/parser.rs:3336:24
  22: nu_parser::parser::parse
             at ./crates/nu-parser/src/parser.rs:3644:25
  23: <nu_cli::syntax_highlight::NuHighlighter as reedline::highlighter::Highlighter>::highlight
             at ./crates/nu-cli/src/syntax_highlight.rs:17:30
  24: reedline::engine::Reedline::buffer_paint
             at /home/stefan/.cargo/git/checkouts/reedline-e42026a78d91c510/3acf7da/src/engine.rs:929:32
  25: reedline::engine::Reedline::repaint
             at /home/stefan/.cargo/git/checkouts/reedline-e42026a78d91c510/3acf7da/src/engine.rs:877:13
  26: reedline::engine::Reedline::run_edit_commands
             at /home/stefan/.cargo/git/checkouts/reedline-e42026a78d91c510/3acf7da/src/engine.rs:800:21
  27: reedline::engine::Reedline::handle_editor_event
             at /home/stefan/.cargo/git/checkouts/reedline-e42026a78d91c510/3acf7da/src/engine.rs:561:17
  28: reedline::engine::Reedline::handle_event
             at /home/stefan/.cargo/git/checkouts/reedline-e42026a78d91c510/3acf7da/src/engine.rs:427:13
  29: reedline::engine::Reedline::read_line_helper
             at /home/stefan/.cargo/git/checkouts/reedline-e42026a78d91c510/3acf7da/src/engine.rs:403:39
  30: reedline::engine::Reedline::read_line
             at /home/stefan/.cargo/git/checkouts/reedline-e42026a78d91c510/3acf7da/src/engine.rs:313:22
  31: engine_q::main
             at ./src/main.rs:403:25
  32: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5

```

**Comment by fdncred** [comment]
I just repro'd this on my Mac moving cursor before x and hitting delete.

**Comment by elferherrera** [comment]
it seems that as soon as you write `in` it panics. There is an issue with the keyword `in` but I cannot find it

**Comment by fdncred** [comment]
I can type `in` just fine and execute a for loop but if I try to edit it and take out the x, it panics.
