### ISSUE TITLE
Panicked after run an alias of `echo`

### ISSUE THREAD

**Issue by hustcer** [nushell/engine-q#620]
Run `alias ec = echo` and then `ec a` will cause panic:
```shell
〉ec thread 'main' panicked at 'internal error: span missing in file contents cache', crates/nu-protocol/src/engine/engine_state.rs:380:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Detail stack trace:
```
〉ec thread 'main' panicked at 'internal error: span missing in file contents cache', crates/nu-protocol/src/engine/engine_state.rs:380:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::panic
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
   3: nu_protocol::engine::engine_state::EngineState::get_span_contents
             at ./crates/nu-protocol/src/engine/engine_state.rs:380:9
   4: nu_protocol::engine::engine_state::StateWorkingSet::get_span_contents
             at ./crates/nu-protocol/src/engine/engine_state.rs:833:20
   5: nu_parser::parser::parse_call
             at ./crates/nu-parser/src/parser.rs:684:20
   6: nu_parser::parser::parse_expression
             at ./crates/nu-parser/src/parser.rs:3162:9
   7: nu_parser::parser::parse_call
             at ./crates/nu-parser/src/parser.rs:697:37
   8: nu_parser::parser::parse_expression
             at ./crates/nu-parser/src/parser.rs:3162:9
   9: nu_parser::parser::parse_statement
             at ./crates/nu-parser/src/parser.rs:3262:31
  10: nu_parser::parser::parse_block::{{closure}}
             at ./crates/nu-parser/src/parser.rs:3405:35
  11: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/adapters/map.rs:84:28
  12: core::iter::traits::iterator::Iterator::fold
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/traits/iterator.rs:2171:21
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/adapters/map.rs:124:9
  14: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/traits/iterator.rs:737:9
  15: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/vec/spec_extend.rs:40:17
  16: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/vec/spec_from_iter_nested.rs:56:9
  17: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/vec/spec_from_iter.rs:33:9
  18: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/vec/mod.rs:2517:9
  19: core::iter::traits::iterator::Iterator::collect
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/traits/iterator.rs:1745:9
  20: <nu_protocol::ast::block::Block as core::convert::From<T>>::from
             at ./crates/nu-protocol/src/ast/block.rs:61:20
  21: <T as core::convert::Into<U>>::into
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/convert/mod.rs:542:9
  22: nu_parser::parser::parse_block
             at ./crates/nu-parser/src/parser.rs:3366:24
  23: nu_parser::parser::parse
             at ./crates/nu-parser/src/parser.rs:3684:25
  24: <nu_cli::syntax_highlight::NuHighlighter as reedline::highlighter::Highlighter>::highlight
             at ./crates/nu-cli/src/syntax_highlight.rs:17:30
  25: reedline::engine::Reedline::prepare_buffer_content
             at /Users/hustcer/.cargo/git/checkouts/reedline-e42026a78d91c510/afa83d9/src/engine.rs:951:32
  26: reedline::engine::Reedline::buffer_paint
             at /Users/hustcer/.cargo/git/checkouts/reedline-e42026a78d91c510/afa83d9/src/engine.rs:979:40
  27: reedline::engine::Reedline::repaint
             at /Users/hustcer/.cargo/git/checkouts/reedline-e42026a78d91c510/afa83d9/src/engine.rs:899:13
  28: reedline::engine::Reedline::run_edit_commands
             at /Users/hustcer/.cargo/git/checkouts/reedline-e42026a78d91c510/afa83d9/src/engine.rs:814:21
  29: reedline::engine::Reedline::handle_editor_event
             at /Users/hustcer/.cargo/git/checkouts/reedline-e42026a78d91c510/afa83d9/src/engine.rs:565:17
  30: reedline::engine::Reedline::handle_event
             at /Users/hustcer/.cargo/git/checkouts/reedline-e42026a78d91c510/afa83d9/src/engine.rs:427:13
  31: reedline::engine::Reedline::read_line_helper
             at /Users/hustcer/.cargo/git/checkouts/reedline-e42026a78d91c510/afa83d9/src/engine.rs:403:39
  32: reedline::engine::Reedline::read_line
             at /Users/hustcer/.cargo/git/checkouts/reedline-e42026a78d91c510/afa83d9/src/engine.rs:313:22
  33: engine_q::main
             at ./src/main.rs:410:25
  34: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by fdncred** [comment]
possible dupe of #612

**Comment by fdncred** [comment]
fixed by #713
