### ISSUE TITLE
Panic when alias has an argument

### ISSUE THREAD

**Issue by kubouch** [nushell/engine-q#702]
EDIT: I updated the issue to match the actual problem

```
> alias foo = bar

> foo .  # when hitting the dot, it won't print the dot and panics with the following message:
thread 'main' panicked at 'internal error: span missing in file contents cache', crates/nu-protocol/src/engine/engine_state.rs:410:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::panic
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
   3: nu_protocol::engine::engine_state::EngineState::get_span_contents
             at ./crates/nu-protocol/src/engine/engine_state.rs:410:9
   4: nu_protocol::engine::engine_state::StateWorkingSet::get_span_contents
             at ./crates/nu-protocol/src/engine/engine_state.rs:863:20
   5: nu_parser::parser::parse_call
             at ./crates/nu-parser/src/parser.rs:753:20
   6: nu_parser::parser::parse_expression
             at ./crates/nu-parser/src/parser.rs:3290:9
   7: nu_parser::parser::parse_call
             at ./crates/nu-parser/src/parser.rs:768:37
   8: nu_parser::parser::parse_expression
             at ./crates/nu-parser/src/parser.rs:3290:9
   9: nu_parser::parser::parse_statement
             at ./crates/nu-parser/src/parser.rs:3390:31
  10: nu_parser::parser::parse_block::{{closure}}
             at ./crates/nu-parser/src/parser.rs:3535:35
  11: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/adapters/map.rs:84:28
  12: core::iter::traits::iterator::Iterator::fold
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/traits/iterator.rs:2171:21
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/adapters/map.rs:124:9
  14: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/traits/iterator.rs:737:9
  15: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/vec/spec_extend.rs:40:17
  16: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/vec/spec_from_iter_nested.rs:56:9
  17: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/vec/spec_from_iter.rs:33:9
  18: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/vec/mod.rs:2517:9
  19: core::iter::traits::iterator::Iterator::collect
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/traits/iterator.rs:1745:9
  20: <nu_protocol::ast::block::Block as core::convert::From<T>>::from
             at ./crates/nu-protocol/src/ast/block.rs:61:20
  21: <T as core::convert::Into<U>>::into
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/convert/mod.rs:542:9
  22: nu_parser::parser::parse_block
             at ./crates/nu-parser/src/parser.rs:3496:24
  23: nu_parser::parser::parse
             at ./crates/nu-parser/src/parser.rs:3819:25
  24: <nu_cli::syntax_highlight::NuHighlighter as reedline::highlighter::Highlighter>::highlight
             at ./crates/nu-cli/src/syntax_highlight.rs:20:30
  25: reedline::engine::Reedline::buffer_paint
             at /home/kubouch/.cargo/git/checkouts/reedline-e42026a78d91c510/373c76a/src/engine.rs:938:45
  26: reedline::engine::Reedline::repaint
             at /home/kubouch/.cargo/git/checkouts/reedline-e42026a78d91c510/373c76a/src/engine.rs:884:13
  27: reedline::engine::Reedline::handle_editor_event
             at /home/kubouch/.cargo/git/checkouts/reedline-e42026a78d91c510/373c76a/src/engine.rs:571:17
  28: reedline::engine::Reedline::handle_event
             at /home/kubouch/.cargo/git/checkouts/reedline-e42026a78d91c510/373c76a/src/engine.rs:434:13
  29: reedline::engine::Reedline::read_line_helper
             at /home/kubouch/.cargo/git/checkouts/reedline-e42026a78d91c510/373c76a/src/engine.rs:409:39
  30: reedline::engine::Reedline::read_line
             at /home/kubouch/.cargo/git/checkouts/reedline-e42026a78d91c510/373c76a/src/engine.rs:319:22
  31: engine_q::main
             at ./src/main.rs:433:25
  32: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jntrnr** [comment]
@kubouch - can't repro this one on Linux Mint with a pretty recent e-q. Are you able to build a debug build and get a backtrace that way?

**Comment by kubouch** [comment]
@jntrnr Here is the full backtrace:
```
thread 'main' panicked at 'internal error: span missing in file contents cache', crates/nu-protocol/src/engine/engine_state.rs:410:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::panicking::panic
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:50:5
   3: nu_protocol::engine::engine_state::EngineState::get_span_contents
             at /home/kubouch/git/forks/engine-q/crates/nu-protocol/src/engine/engine_state.rs:410:9
   4: nu_protocol::engine::engine_state::StateWorkingSet::get_span_contents
             at /home/kubouch/git/forks/engine-q/crates/nu-protocol/src/engine/engine_state.rs:863:20
   5: nu_parser::parser::parse_call
             at ./crates/nu-parser/src/parser.rs:753:20
   6: nu_parser::parser::parse_expression
             at ./crates/nu-parser/src/parser.rs:3290:9
   7: nu_parser::parser::parse_call
             at ./crates/nu-parser/src/parser.rs:768:37
   8: nu_parser::parser::parse_expression
             at ./crates/nu-parser/src/parser.rs:3290:9
   9: nu_parser::parser::parse_statement
             at ./crates/nu-parser/src/parser.rs:3390:31
  10: nu_parser::parser::parse_block::{{closure}}
             at ./crates/nu-parser/src/parser.rs:3535:35
  11: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/adapters/map.rs:84:28
  12: core::iter::traits::iterator::Iterator::fold
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/traits/iterator.rs:2171:21
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/adapters/map.rs:124:9
  14: core::iter::traits::iterator::Iterator::for_each
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/traits/iterator.rs:737:9
  15: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/vec/spec_extend.rs:40:17
  16: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/vec/spec_from_iter_nested.rs:56:9
  17: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/vec/spec_from_iter.rs:33:9
  18: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/vec/mod.rs:2517:9
  19: core::iter::traits::iterator::Iterator::collect
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/iter/traits/iterator.rs:1745:9
  20: <nu_protocol::ast::block::Block as core::convert::From<T>>::from
             at /home/kubouch/git/forks/engine-q/crates/nu-protocol/src/ast/block.rs:61:20
  21: <T as core::convert::Into<U>>::into
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/convert/mod.rs:542:9
  22: nu_parser::parser::parse_block
             at ./crates/nu-parser/src/parser.rs:3496:24
  23: nu_parser::parser::parse
             at ./crates/nu-parser/src/parser.rs:3819:25
  24: <nu_cli::syntax_highlight::NuHighlighter as reedline::highlighter::Highlighter>::highlight
             at ./crates/nu-cli/src/syntax_highlight.rs:20:30
  25: reedline::engine::Reedline::buffer_paint
             at /home/kubouch/.cargo/git/checkouts/reedline-e42026a78d91c510/373c76a/src/engine.rs:938:45
  26: reedline::engine::Reedline::repaint
             at /home/kubouch/.cargo/git/checkouts/reedline-e42026a78d91c510/373c76a/src/engine.rs:884:13
  27: reedline::engine::Reedline::handle_editor_event
             at /home/kubouch/.cargo/git/checkouts/reedline-e42026a78d91c510/373c76a/src/engine.rs:571:17
  28: reedline::engine::Reedline::handle_event
             at /home/kubouch/.cargo/git/checkouts/reedline-e42026a78d91c510/373c76a/src/engine.rs:434:13
  29: reedline::engine::Reedline::read_line_helper
             at /home/kubouch/.cargo/git/checkouts/reedline-e42026a78d91c510/373c76a/src/engine.rs:409:39
  30: reedline::engine::Reedline::read_line
             at /home/kubouch/.cargo/git/checkouts/reedline-e42026a78d91c510/373c76a/src/engine.rs:319:22
  31: engine_q::main
             at ./src/main.rs:433:25
  32: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Version:
```
╭────────────────────┬──────────────────────────────────────────╮
│ version            │ 0.1.0                                    │
│ branch             │ reduce-command                           │
│ short_commit       │ f964ce9b                                 │
│ commit_hash        │ f964ce9bc00771708b217340ae2df30cf18ded0a │
│ commit_date        │ 2022-01-07 11:44:05 +00:00               │
│ build_os           │ linux-x86_64                             │
│ rust_version       │ rustc 1.57.0 (f1edd0429 2021-11-29)      │
│ rust_channel       │ stable-x86_64-unknown-linux-gnu          │
│ cargo_version      │ cargo 1.57.0 (b2e52d7ca 2021-10-21)      │
│ pkg_version        │ 0.1.0                                    │
│ build_time         │ 2022-01-08 00:42:11 +02:00               │
│ build_rust_channel │ debug                                    │
│ features           │ default                                  │
│ installed_plugins  │ gstat                                    │
╰────────────────────┴──────────────────────────────────────────╯
```

**Comment by kubouch** [comment]
Maybe it has to do something with completions

**Comment by fdncred** [comment]
I can't repro it on Mac. Does it only happen with `ls .` because I'm wondering, if it's something related to completions, like you theorize, you may have something interesting in your history that starts with a `.`.

**Comment by kubouch** [comment]
Ha, I figured out why it happens! I have this in my config:
```
alias s = shells
``` 

When you delete the `l` you end up with `s .` which triggers the panic. Typing `s .` manually panics while `shells .` doesn't. Seems like a bug in alias.

**Comment by fdncred** [comment]
aliases have been broke for a while.
https://github.com/nushell/engine-q/issues/620
https://github.com/nushell/engine-q/issues/612

**Comment by jntrnr** [comment]
I can see what's happening. Writing it down before I forget.

Steps for repro:
```
> alias s = shells
> s .
```

The alias sets up an expansion, and this expansion will expand into a Span that points into the permanent state in the parser (since it came from a previous line).

When you type `s .`, it does because it expands to `shells .` but the `shells` part of that expression comes from a different part in the cache of source files. So when we create a span that covers both `shells .` when we're looking for subcommands, we create a span that can't be: one that spans both the permanent and working set. The end result fails to be found, and then we panic.
